site_name: Download Toolbox
theme:
  name: material
  highlightjs: true
nav:
  - Home: 'index.md'
  - 'usage.md'
  - API:
    - download_toolbox.data:
      - "download_toolbox/data/amsr.md"
      - "download_toolbox/data/cds.md"
      - "download_toolbox/data/esgf.md"
      - "download_toolbox/data/osisaf.md"
      - "download_toolbox/data/utils.md"
    - "download_toolbox/cli.md"
    - "download_toolbox/download.md"
    - "download_toolbox/location.md"
    - "download_toolbox/base.md"
    - "download_toolbox/config.md"
    - "download_toolbox/dataset.md"
    - "download_toolbox/interface.md"
    - "download_toolbox/time.md"
    - "download_toolbox/utils.md"
  - GitHub: 'https://github.com/environmental-forecasting/download-toolbox'
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
            heading_level: 3
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
